ReservationSystem : ReservationSystem.h ReservationSystem.cpp Flight.cpp Flight.h Reservation.cpp Reservation.h main.cpp
	g++ ReservationSystem.h ReservationSystem.cpp Flight.cpp Flight.h Reservation.cpp Reservation.h main.cpp -o ReservationSystem

Remove :
	rm -f ReservationSystem
